"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#ffffff)\
$os\
$username\
[](fg:#ffffff bg:#333333)\
$directory\
[](fg:#333333 bg:#222222)\
$git_branch\
$git_status\
[](fg:#222222)\
$fill\
$cmd_duration\
$python\
$nodejs\
$rust\
$golang\
$java\
$docker_context\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#ffffff fg:#000000 bold"

[os.symbols]
Ubuntu = " "
Linux = " "
Macos = " "
Windows = "󰍲 "

[username]
show_always = false
style_user = "bg:#ffffff fg:#000000 bold"
format = '[$user ]($style)'

[directory]
style = "bg:#333333 fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#222222 fg:#aaaaaa"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#222222 fg:#888888"
format = '[$all_status$ahead_behind ]($style)'

[fill]
symbol = " "

[cmd_duration]
min_time = 2_000
style = "fg:#888888"
format = '[ 󰔛 $duration]($style) '

[character]
success_symbol = "[❯](bold fg:#ffffff)"
error_symbol = "[❯](bold fg:#ff5555)"

[python]
symbol = " "
style = "fg:#aaaaaa"
format = '[$symbol$version]($style) '

[nodejs]
symbol = " "
style = "fg:#aaaaaa"
format = '[$symbol$version]($style) '

[rust]
symbol = " "
style = "fg:#aaaaaa"
format = '[$symbol$version]($style) '

[golang]
symbol = " "
style = "fg:#aaaaaa"
format = '[$symbol$version]($style) '

[java]
symbol = " "
style = "fg:#aaaaaa"
format = '[$symbol$version]($style) '

[docker_context]
symbol = " "
style = "fg:#aaaaaa"
format = '[$symbol$context]($style) '
